name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Ajuste para a versão do PHP que você está utilizando
        extensions: mbstring, xml, bcmath, curl, zip  # Adicione extensões necessárias

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    - name: Generate application key
      run: php artisan key:generate

    - name: Run database migrations
      run: php artisan migrate --env=testing

    - name: Run tests
      run: vendor/bin/phpunit
