name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    # Adicione um script de teste ao seu composer.json, por exemplo:
    # "scripts": {
    #   "test": "vendor/bin/phpunit"
    # }
    {
    "name": "kental1983/Calculadora_ipv4",
    "description": "Descrição do seu projeto",
    "require": {
        // suas dependências
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5"  // Certifique-se de usar a versão adequada para seu PHP
    },
    "scripts": {
        "test": "vendor/bin/phpunit"
    }
}

    
    - name: Run test suite
      run: composer run-script test
